version: '3'

services:

  router1:
    container_name: router1
    image: mongo:6.0.1
    command: mongos --configdb cfg1/cfg1:27017 --bind_ip 0.0.0.0 --port 27017
    # healthcheck:
    #   test: echo 'db.runCommand("ping").ok' | mongosh router1:27017/test --quiet
    #   interval: 10s
    #   timeout: 10s
    #   retries: 5
    #   start_period: 40s
    ports:
      - 27100:27017
    volumes:
      - ./dataset:/dataset
      - ./init_scripts:/init_scripts
      - router1_db:/data/db
      - router1_cfg:/data/configdb
    depends_on:
      - dbms1-svr1
      - dbms1-svr2
      - dbms2-svr1
      - dbms2-svr2


  router2:
    container_name: router2
    image: mongo:6.0.1
    command: mongos --configdb cfg2/cfg2:27017 --bind_ip 0.0.0.0 --port 27017
    ports:
      - 27101:27017
    volumes:
      - ./dataset:/dataset
      - ./init_scripts:/init_scripts
      - router2_db:/data/db
      - router2_cfg:/data/configdb
  
  cfg1:
    container_name: cfg1
    image: mongo:6.0.1
    command: mongod --configsvr --replSet cfg1 --port 27017 --dbpath /data/db
    ports:
      - 27200:27017
    volumes:
      - ./init_scripts:/init_scripts
      - cfg1_db:/data/db
      - cfg1_cfg:/data/configdb

  cfg2:
    container_name: cfg2
    image: mongo:6.0.1
    command: mongod --configsvr --replSet cfg2 --port 27017 --dbpath /data/db
    ports:
      - 27201:27017
    volumes:
      - ./init_scripts:/init_scripts
      - cfg2_db:/data/db
      - cfg2_cfg:/data/configdb

  dbms1-svr1:
    container_name: dbms1-svr1
    image: mongo:6.0.1
    command: mongod --shardsvr --replSet dbms1 --port 27017 --dbpath /data/db
    ports:
      - 27300:27017
    volumes:
      - ./init_scripts:/init_scripts
      - dbms1-svr1_db:/data/db
      - dbms1-svr1_cfg:/data/configdb
  
  dbms1-svr2:
    container_name: dbms1-svr2
    image: mongo:6.0.1
    command: mongod --shardsvr --replSet dbms1 --port 27017 --dbpath /data/db
    ports:
      - 27301:27017
    volumes:
      - ./init_scripts:/init_scripts
      - dbms1-svr2_db:/data/db
      - dbms1-svr2_cfg:/data/configdb

  dbms2-svr1:
    container_name: dbms2-svr1
    image: mongo:6.0.1
    command: mongod --shardsvr --replSet dbms2 --port 27017 --dbpath /data/db
    ports:
      - 27310:27017
    volumes:
      - ./init_scripts:/init_scripts
      - dbms2-svr1_db:/data/db
      - dbms2-svr1_cfg:/data/configdb

  dbms2-svr2:
    container_name: dbms2-svr2
    image: mongo:6.0.1
    command: mongod --shardsvr --replSet dbms2 --port 27017 --dbpath /data/db
    ports:
      - 27311:27017
    volumes:
      - ./init_scripts:/init_scripts
      - dbms2-svr2_db:/data/db
      - dbms2-svr2_cfg:/data/configdb
  # shard_for_init1:
  #   container_name: shard_for_init1
  #   image: mongo:6.0.1
  #   command: mongod --shardsvr --replSet shard_for_init1 --port 27017 --dbpath /data/db
  #   ports:
  #     - 27302:27017
  #   volumes:
  #     - ./init_scripts:/init_scripts
  #     - shard_for_init1_db:/data/db
  #     - shard_for_init1_cfg:/data/configdb

  gridfs1:
    container_name: gridfs1
    image: mongo:6.0.1
    command: mongod --shardsvr --replSet gridfs1 --port 27017 --dbpath /data/db
    ports:
      - 27400:27017
    volumes:
      - ./init_scripts:/init_scripts
      - gridfs1_db:/data/db
      - gridfs1_cfg:/data/configdb
  
  gridfs2:
    container_name: gridfs2
    image: mongo:6.0.1
    command: mongod --shardsvr --replSet gridfs2 --port 27017 --dbpath /data/db
    ports:
      - 27401:27017
    volumes:
      - ./init_scripts:/init_scripts
      - gridfs2_db:/data/db
      - gridfs2_cfg:/data/configdb

  monitor1:
    container_name: monitor1
    image: mongo-express:latest
    environment:
      ME_CONFIG_MONGODB_SERVER: router1
      ME_CONFIG_MONGODB_PORT: 27017
      # ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      # ME_CONFIG_MONGODB_URL: mongodb://router1:27017/
      # ME_CONFIG_BASICAUTH_USERNAME: root
      # ME_CONFIG_BASICAUTH_PASSWORD: root
    ports:
      - "8081:8081"
    depends_on:
      - router1
    restart: always
    #     condition: service_healthy

  # monitor2:
  #   container_name: monitor2
  #   image: mongo-express
  #   environment:
  #     ME_CONFIG_MONGODB_SERVER: router2
  #     ME_CONFIG_MONGODB_PORT: "27017"
  #     ME_CONFIG_BASICAUTH_USERNAME: root
  #     ME_CONFIG_BASICAUTH_PASSWORD: root
  #   ports:
  #     - "8002:8081"
  #   depends_on:
  #     - router2


volumes:
  router1_db:
  router1_cfg:
  router2_db:
  router2_cfg:
  cfg1_db:
  cfg1_cfg:
  cfg2_db:
  cfg2_cfg:
  dbms1-svr1_db:
  dbms1-svr1_cfg:
  dbms1-svr2_db:
  dbms1-svr2_cfg:
  dbms2-svr1_db:
  dbms2-svr1_cfg:
  dbms2-svr2_db:
  dbms2-svr2_cfg:
  # shard_for_init1_db:
  # shard_for_init1_cfg:
  gridfs1_db:
  gridfs1_cfg:
  gridfs2_db:
  gridfs2_cfg:
  