version: '3'

services:

  router1:
    container_name: router1
    image: mongo:6.0.1
    command: mongos --configdb cfg1/cfg1:27017 --bind_ip 0.0.0.0 --port 27017
    ports:
      - 27100:27017
    volumes:
      - ./dataset:/dataset
      - ./init_scripts:/init_scripts
      - router1_db:/data/db
      - router1_cfg:/data/configdb

  router2:
    container_name: router2
    image: mongo:6.0.1
    command: mongos --configdb cfg2/cfg2:27017 --bind_ip 0.0.0.0 --port 27017
    ports:
      - 27101:27017
    volumes:
      - ./dataset:/dataset
      - ./init_scripts:/init_scripts
      - router2_db:/data/db
      - router2_cfg:/data/configdb
  
  cfg1:
    container_name: cfg1
    image: mongo:6.0.1
    command: mongod --configsvr --replSet cfg1 --port 27017 --dbpath /data/db
    ports:
      - 27200:27017
    volumes:
      - ./init_scripts:/init_scripts
      - cfg1_db:/data/db
      - cfg1_cfg:/data/configdb

  cfg2:
    container_name: cfg2
    image: mongo:6.0.1
    command: mongod --configsvr --replSet cfg2 --port 27017 --dbpath /data/db
    ports:
      - 27201:27017
    volumes:
      - ./init_scripts:/init_scripts
      - cfg2_db:/data/db
      - cfg2_cfg:/data/configdb

  dmbs1:
    container_name: dbms1
    image: mongo:6.0.1
    command: mongod --shardsvr --replSet dbms1 --port 27017 --dbpath /data/db
    ports:
      - 27300:27017
    volumes:
      - ./init_scripts:/init_scripts
      - dbms1_db:/data/db
      - dbms1_cfg:/data/configdb

  dmbs2:
    container_name: dbms2
    image: mongo:6.0.1
    command: mongod --shardsvr --replSet dbms2 --port 27017 --dbpath /data/db
    ports:
      - 27301:27017
    volumes:
      - ./init_scripts:/init_scripts
      - dbms2_db:/data/db
      - dbms2_cfg:/data/configdb

  gridfs1:
    container_name: gridfs1
    image: mongo:6.0.1
    command: mongod --shardsvr --replSet gridfs1 --port 27017 --dbpath /data/db
    ports:
      - 27400:27017
    volumes:
      - ./init_scripts:/init_scripts
      - gridfs1_db:/data/db
      - gridfs1_cfg:/data/configdb
  
  gridfs2:
    container_name: gridfs2
    image: mongo:6.0.1
    command: mongod --shardsvr --replSet gridfs2 --port 27017 --dbpath /data/db
    ports:
      - 27401:27017
    volumes:
      - ./init_scripts:/init_scripts
      - gridfs2_db:/data/db
      - gridfs2_cfg:/data/configdb


volumes:
  router1_db:
  router1_cfg:
  router2_db:
  router2_cfg:
  cfg1_db:
  cfg1_cfg:
  cfg2_db:
  cfg2_cfg:
  dbms1_db:
  dbms1_cfg:
  dbms2_db:
  dbms2_cfg:
  gridfs1_db:
  gridfs1_cfg:
  gridfs2_db:
  gridfs2_cfg:
  